export const COVID_GLOBAL_LIVETRACKING_FETCH_DATA = "COVID_GLOBAL_LIVETRACKING_FETCH_DATA";
export const COVID_GLOBAL_LIVETRACKING_FETCH_SUCCESS = "COVID_GLOBAL_LIVETRACKING_FETCH_SUCCESS";
export const COVID_GLOBAL_LIVETRACKING_FETCH_ERR = "COVID_GLOBAL_LIVETRACKING_FETCH_ERR";
export const COVID_GLOBAL_LIVETRACKING_FETCH_END = "COVID_GLOBAL_LIVETRACKING_FETCH_END";
